name: "Terraform Plan Action"
description: "Executes Terraform Plan quickly"
author: "gusvega.dev"

inputs:
  workdir:
    description: "Working directory for Terraform"
    required: false
    default: "."

outputs:
  plan_status:
    description: "Terraform Plan execution status"

runs:
  using: "node20"
  main: "index.js"
