name: "Terraform Plan Action"
description: "Executes Terraform Plan inside a container"
author: "gusvega"

inputs:
  workdir:
    description: "Working directory for Terraform"
    required: false
    default: "."

outputs:
  plan_status:
    description: "Terraform Plan execution status"

runs:
  using: "docker"
  image: "docker://ghcr.io/gusvega-dev/tf-plan-gcp:v1.0.1"
