name: "Terraform Plan for GCP"
description: "Runs Terraform plan without containers"
author: "Gus Vega"

inputs:
  tf_working_directory:
    description: "Path to the Terraform directory"
    required: false
    default: "."
  tf_version:
    description: "Terraform version to install"
    required: false
    default: "1.5.0"

outputs:
  plan_output:
    description: "Terraform plan output"

runs:
  using: "node20"
  main: "index.js"

branding:
  icon: "terminal"
  color: "blue"
