name: "Terraform Plan GCP Action"
description: "Executes Terraform Plan inside a container"
author: "gusvega"
branding:
  icon: "cloud"
  color: "red"

inputs:
  workdir:
    description: "Working directory for Terraform"
    required: false
    default: "."

outputs:
  plan_status:
    description: "Terraform Plan execution status"

runs:
  using: "docker"
  image: "docker://ghcr.io/gusvega-dev/tf-plan-gcp:v1.0.1"

description: "Run Terraform Plan in a containerized GitHub Action for GCP, built by Gus Vega. No Terraform install required."
