name: "Terraform Plan Action"
description: "A paid GitHub Action for Terraform Plan"
author: "Your Org"

inputs:
  workdir:
    description: "Working directory for Terraform"
    required: false
    default: "."

outputs:
  plan_status:
    description: "Status of Terraform Plan execution"

runs:
  using: "docker"
  image: "docker://ghcr.io/gusvega-dev/tf-plan-gcp:latest"
