name: "Terraform Plan Action"
description: "A GitHub Action to automate Terraform Init & Plan in CI/CD pipelines"
author: "Gus Vega"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  tf_version:
    description: "Terraform version to use"
    required: false
    default: "1.5.6"

  workdir:
    description: "Working directory where Terraform configuration files are located"
    required: false
    default: "."

outputs:
  plan_status:
    description: "Status of Terraform Plan execution"

runs:
  using: "node20"
  main: "index.js"
  pre: "npm install"
