name: Publish Docker-Based GitHub Action to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write  # Allow pushing to GHCR
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        env:
          IMAGE_NAME: ghcr.io/gusvega-dev/tf-plan-gcp
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(date +%Y%m%d%H%M%S)

      - name: Push Docker Image to GHCR
        env:
          IMAGE_NAME: ghcr.io/gusvega-dev/tf-plan-gcp
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$(date +%Y%m%d%H%M%S)

      - name: Set Image Visibility to Private
        run: |
          gh api \
            --method PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            /orgs/gusvega-dev/packages/container/tf-plan-gcp \
            -f visibility=private
