name: Publish JavaScript GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Action
        run: npm run build || echo "No build step needed"

      - name: Create and Push Tag (Latest)
        run: |
          git tag -f latest
          git push origin -f latest
